### ISSUE TITLE
New version lo longer working

### ISSUE THREAD

**Issue by Castyblank320** [loaforcsSoundAPI/loaforcsSoundAPI.Examples#1]
since the update for the v50 this method to replace the music of the music of the FacilityMeltdown mod no longer works
[MySoundPack.zip](https://github.com/LoafOrc/loaforcsSoundAPI-examples/files/14969081/MySoundPack.zip)
File i'm using.

**Comment by LoafOrc** [comment]
oh yeah 💀 
this came from me changing the audio clip on facility meltdown, fixing it now
